### ISSUE TITLE
All things can be abused. But should they?

### ISSUE THREAD

**Issue by DomiiBunn** [CoolElectronics/bookmarkfs#3]
I just hope we're all aware that this will probably cause google to either heavily limit what can be synced in chrome or make paid tiers. As cool as the project is it'll most likely effect people in a negative way due to it's abuse of googles api

**Comment by GreenReaper** [comment]
Better that it be abused for good rather than evil.

**Comment by ArjixWasTaken** [comment]
> I just hope we're all aware that this will probably cause google to either heavily limit what can be synced in chrome or make paid tiers. As cool as the project is it'll most likely effect people in a negative way due to it's abuse of googles api

ah yes, cause you have like a million bookmarks and will be affected by any limit google decides to add....
of course that is not the case, worst case scenario google sets a limit of 100mb

if you think 100mb is too little...then remember that a single ASCII character is a byte (well, 7 bits, but stored as a byte)
100mb are roughly 1K KB, and 1K KB are roughly 100.000.000 bytes...aka 100.000.000 characters

how much text is 100.000.000 characters?
considering bookmarks are plain text (with the possibility of storing a small icon), that is a lot

the link to this issue (with a newline at the end) can be repeated 99.999.955 times until you can't store it anymore


> simple python code to check

```python
goal_len = 100_000_000

a = 0
url = len("https://github.com/CoolElectronics/bookmarkfs/issues/3\n")

while a + url < goal_len:
	a += url

print(a)
```
so depending on how efficiently google stores the bookmarks, you could have 100~ million bookmarks even with a 100mb limit.

I know these numbers are not calculating a lot of things, like in what way chrome stores the bookmarks, but even if the limit was 30mb, that would at least be more than 10 million bookmarks (if not close to 30 million)

if chrome can even render that many bookmarks at once, your client would most likely crash before you can even reach 5 million

I myself have less than 1.000 bookmarks, most of my friends have less than 2.000 bookmarks, i can't imagine a person even reaching 1.000.000 bookmarks, thats a huge number

**Comment by randspace0** [comment]
Is this supposed to be a joke?

**Comment by DomiiBunn** [comment]
You guys do you
