### ISSUE TITLE
More efficient encoding

### ISSUE THREAD

**Issue by NexusXe** [CoolElectronics/bookmarkfs#4]
Hello. I feel as if the use of base64 is severely limiting the storage-per-bookmark that can be utilized here, as the bookmarks accept much more than the 64 different characters being used. Data density could be increased substantially by using more bits per character. I feel as if a custom encoding scheme might be most useful, as certain characters and character combinations might not work very nicely with the bookmarks system.

**Comment by velzie** [comment]
Thanks for the suggestion! After some preliminary testing, it seems that the title section of a bookmark will accept any unicode character, meaning I could use a system such as [base65336](https://github.com/qntm/base65536). I'll see if it's possible to include that into the extension, or possibly even use a compression algorithim such as gzip for increasing the file density.

**Comment by NexusXe** [comment]
If compression is on the table, I feel as if Zstandard would be a better choice, especially considering how poorly gzip handles incompressible data like photos and videos.

**Comment by velzie** [comment]
Did a quick google, couldn't seem to find any pure js implementations of that compression. I'll keep trying to find something that works.

**Comment by velzie** [comment]
Unfortunately, the cutoff for chrome sync seems to be based off of byte size rather than string length, so anything above base64 will be less efficient. The latest release now uses Gzip compression, but it usually doesn't save too much space on images and videos.
