### ISSUE TITLE
Nothing happening after selecting file

### ISSUE THREAD

**Issue by TheTechFrog** [CoolElectronics/bookmarkfs#7]
After I select my file there are no additional options like in the video

**Comment by velzie** [comment]
By additional options, are you referring to the box with the download and delete buttons?
Can you please provide additional details, eg. how big was the file, are there any errors in developer tools, etc

**Comment by TheTechFrog** [comment]
Yes, I am referring to those, the file was 114 KB, it was a .jpg file, I also tried a .exe file size 263 KB, but I'm not sure how to view the error logs. I tried the extension in both google chrome and another chromium-based browser, but neither worked.

**Comment by velzie** [comment]
You can open developer tools with Ctrl-Shift-I or by pressing F12 as you would on any other page

**Comment by TheTechFrog** [comment]
Failed to load resource: net::ERR_FILE_NOT_FOUND bundle.js:1

**Comment by TheTechFrog** [comment]
Also, the .crx file on the releases page was giving the error Package is invalid: CRX_REQUIERD_PROOF_MISSING. when I downloaded it. I downloaded the source code and then clicked load unpacked on chrome://extensions to get the extension.

**Comment by velzie** [comment]
If you want to run it from source code, there's a build step, the instructions for building are listed in the readme. Otherwise, you want to install the bookmarkfs.crx file in the releases tab and follow the installation instructions
